apiVersion: v1
kind: PersistentVolume
metadata:
  name: rag-models-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/zenteiq/Documents/test-embed/gen_embed_prod/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-models-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  volumeName: rag-models-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rag-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/zenteiq/Documents/Learnings/rag-factory-pipeline/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: rag-data-pv
  storageClassName: ""
